export const enum Instruction {
  AccountQuery = "accountQuery",
  BalanceQuery = "balanceQuery",
  BorrowLendExecute = "borrowLendExecute",
  BorrowHistoryQueryAll = "borrowHistoryQueryAll",
  CollateralQuery = "collateralQuery",
  DepositAddressQuery = "depositAddressQuery",
  DepositQueryAll = "depositQueryAll",
  FillHistoryQueryAll = "fillHistoryQueryAll",
  FundingHistoryQueryAll = "fundingHistoryQueryAll",
  InterestHistoryQueryAll = "interestHistoryQueryAll",
  OrderCancel = "orderCancel",
  OrderCancelAll = "orderCancelAll",
  OrderExecute = "orderExecute",
  OrderHistoryQueryAll = "orderHistoryQueryAll",
  OrderQuery = "orderQuery",
  OrderQueryAll = "orderQueryAll",
  PnlHistoryQueryAll = "pnlHistoryQueryAll",
  PositionQuery = "positionQuery",
  QuoteSubmit = "quoteSubmit",
  Withdraw = "withdraw",
  WithdrawalQueryAll = "withdrawalQueryAll",
}